[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "testflow"
version = "0.1.0"
description = "TestFlow atoms script runner"
authors = [{ name = "TestFlow_team" }]
dependencies = []

[tool.setuptools]
packages = ["testflow"]
